// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbfoeuqorfgawvbqpsxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpiZm9ldXFvcmZnYXd2YnFwc3hoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NjAwNjksImV4cCI6MjA2MzMzNjA2OX0.iXDf6EobEPfWpHKLuF0V_kdTzS1Ko9A6217ggpCgxGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);